### ISSUE TITLE
Colour mode doesn't change

### ISSUE THREAD

**Issue by aadnegture** [donkirkby/svg-turtle#1]
Hi, your library looked like it could come in handy for me, thanks! 
However, there seems to be a problem with colors in dots. Running:
```
t = SvgTurtle(500, 500)  
t.penup()  
t.forward(200)  
t.dot(30,(17, 103, 45))  
t.save_as('example.svg')
```
Produces a dot, but colored black in stead of green:
![image](https://user-images.githubusercontent.com/91458900/151439893-38be70a5-1b84-4979-a9fd-c40478f305e0.png)

**Comment by donkirkby** [comment]
Thanks for the bug report.

You're not quite using the colour commands the way that the turtle module expects. If I switch your example code back to using the regular turtle module, you can see the problem:

    import turtle as t
    
    t.penup()
    t.forward(200)
    t.dot(30,(17, 103, 45))
    
    t.done()

If I run that code, the call to `dot()` fails:

    turtle.TurtleGraphicsError: bad color sequence: (17, 103, 45)

By default, the turtle module expects colour values to be between 0 and 1, so dividing the RGB values by 255 makes both the turtle module and `SvgTurtle` happy.

    from svg_turtle import SvgTurtle
    
    t = SvgTurtle(500, 500)
    t.penup()
    t.forward(200)
    t.dot(30, (17/255, 103/255, 45/255))
    t.save_as('example.svg')

However, you should also be able to change the colour mode to 255. Then it should behave the way you were expecting. That works with the regular turtle module, but not with `SvgTurtle`, so I'll fix that bug.

    import turtle as t
    
    t.getscreen().colormode(255)
    t.penup()
    t.forward(200)
    t.dot(30,(17, 103, 45))
    
    t.done()
