### ISSUE TITLE
Unexpected fill between dots

### ISSUE THREAD

**Issue by aadnegture** [donkirkby/svg-turtle#2]
Hi, thanks for clearing up issue #1 .
I noticed that there's a difference between turtle and svgturtle.
Running:
```
t = SvgTurtle(1000,1000)
t.penup()
t.hideturtle()
t.forward(200)
t.dot(30,(17/255, 103/255, 45/255))
t.forward(50)
t.dot(30,(17/255,232/255,122/255))
t.save_as('example.svg')
```
Gives the right color, but between dots there's also color:
![image](https://user-images.githubusercontent.com/91458900/151553153-c42b6d20-b949-4679-9051-7e7caf4980c9.png)
Whereas running:
```
k = Turtle()
k.penup()
k.hideturtle()
k.forward(200)
k.speed('fastest')
k.dot(20,(27/255,223/255,45/255))
k.forward(50)
k.dot(20,(27/255,223/255,45/255))
screen = Screen()
screen.exitonclick()
```
Produces just the dots:
![image](https://user-images.githubusercontent.com/91458900/151553287-93152242-5b05-40ef-bef6-57fe7f90f2ec.png)

**Comment by donkirkby** [comment]
Looks like you've found more details about donkirkby/live-py-plugin#362. I guess several pieces of the pen state get messed up.
As a workaround, use a clone of the turtle to draw the dot:

    from svg_turtle import SvgTurtle
    
    t = SvgTurtle(1000,1000)
    t.penup()
    t.hideturtle()
    t.forward(200)
    t.clone().dot(30,(17/255, 103/255, 45/255))
    t.forward(50)
    t.dot(30,(17/255,232/255,122/255))
    t.save_as('example.svg')
