### ISSUE TITLE
AttributeError: 'Canvas' object has no attribute 'winfo_toplevel'

### ISSUE THREAD

**Issue by halessi** [donkirkby/svg-turtle#3]
`from svg_turtle import SvgTurtle`

`t = SvgTurtle(2000, 1600)`

Leads to:

``` 
File "/Users/alessihd/Documents/projects/WES_analysis_10_web/app/functions/plot.py", line 20, in plot
    t = SvgTurtle(2000, 1600)
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/site-packages/svg_turtle/svg_turtle.py", line 118, in __init__
    screen = self._Screen(canvas)
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/site-packages/svg_turtle/svg_turtle.py", line 27, in __init__
    super().__init__(canvas)
  File "/Users/alessihd/opt/miniconda3/envs/py36/lib/python3.6/turtle.py", line 1000, in __init__
    rootwindow = cv.winfo_toplevel()
AttributeError: 'Canvas' object has no attribute 'winfo_toplevel'
```

Thanks for your help!!

Hugh

**Comment by donkirkby** [comment]
Might be a problem with Python 3.6, which I don't test since it ended support last year. Is upgrading to a newer Python possible for you?

**Comment by halessi** [comment]
I tried python 3.7 and same error. Which should I try? Thanks so much for the quick reply!

**Comment by donkirkby** [comment]
Strange. Can you tell me the exact version of Python that you're running, which operating system and version, as well as any other packages you've installed in Python?
Can you paste the stack trace you get from Python 3.7?

**Comment by donkirkby** [comment]
I reproduced the issue by running GitHub Actions on MacOS. Now, I'll see if I can fix it.

**Comment by halessi** [comment]
Thanks so much for fixing this! I ended up abandoning the use of turtle and opting for something more capable, but your quick fix is nonetheless appreciated

**Comment by donkirkby** [comment]
What did you end up using?

**Comment by halessi** [comment]
Went to web development lol and rendering via html/css/js
