### ISSUE TITLE
Layering issue with SVG

### ISSUE THREAD

**Issue by sp1dev** [donkirkby/svg-turtle#37]
My Turtle image comes out as expected (it's the top of a cone with 3 scoops of ice cream) :
![ice-cream-turtle](https://github.com/user-attachments/assets/fbdcb7d2-317a-4d89-b7b2-648cebad3b58)
However, when I create the SVG image, the lines from the background (the pink lines) are appearing in the foreground:
![ice-cream-svg](https://github.com/user-attachments/assets/11535b84-e697-47f7-a122-c64e5eda8cdb)
What can I do so that the background elements stay in the background? I draw all background elements first, but it seems to not work how I expect. I just installed svg_turtle today, using pipenv and pip.
Please advise.

**Comment by donkirkby** [comment]
Good find! I think I might have hacked the outlines separate from the fill, and you've found a case that breaks. I'll dig into what's happening.

For my notes, here's a full example that produces different turtle window and SVG file:

```
import turtle as tmod
from pathlib import Path

from svg_turtle import SvgTurtle


def draw(t):
    t.begin_fill()
    t.color('blue')
    t.circle(100)
    t.end_fill()

    t.begin_fill()
    t.color('red')
    t.forward(100)
    t.circle(100)
    t.end_fill()


def svg_demo():
    svgt = SvgTurtle()
    draw(svgt)
    out_file = Path(__file__).parent / 'scratch.svg'
    out_file.write_text(svgt.to_svg())


def turtle_demo():
    draw(tmod)
    tmod.done()


def main():
    if False:
        svg_demo()
    else:
        turtle_demo()


main()
```
