### ISSUE TITLE
svg-turtle + svglib (convert to png)

### ISSUE THREAD

**Issue by inteon** [donkirkby/svg-turtle#4]
It seems like using svglib to render to svg to png can yield incomplete results:
```python
from io import BytesIO
from PIL import Image
from svg_turtle import SvgTurtle
from svglib.svglib import svg2rlg
from reportlab.graphics.renderPM import drawToString

t = SvgTurtle(500, 500)

t.forward(200)
t.dot(10)
t.forward(10)

svg_text = t.to_svg()
svg_bytes = svg_text.encode()
drawing = svg2rlg(BytesIO(svg_bytes))
png_bytes = BytesIO(drawToString(drawing, "PNG"))
image = Image.open(png_bytes)
image_alpha = image.convert("RGBA")
image_alpha.save("image.png", "PNG")

t.save_as("image.svg")
```

This script results in the following outputs:
"image.svg"
![image](https://user-images.githubusercontent.com/42113979/152997235-ba806fe0-3ec8-4f06-b62b-38600c08faab.svg)
"image.png" <- dot is missing!!
![image](https://user-images.githubusercontent.com/42113979/152997213-a8d07fc5-5e25-4d78-9d44-d04da0cd87b3.png)

@donkirkby Have you encountered this problem before? Is this a bug in svglib?

**Comment by inteon** [comment]
Seems to work just fine with cairo (might be useful to add in the README):
```python
from io import BytesIO
from PIL import Image
from svg_turtle import SvgTurtle
from cairosvg import svg2png

t = SvgTurtle(500, 500)

t.forward(200)
t.dot(10)
t.forward(10)

svg_text = t.to_svg()
svg_bytes = svg_text.encode()

png_bytes = BytesIO()
svg2png(bytestring=svg_bytes, write_to=png_bytes)
image = Image.open(png_bytes)

image.save("image.png")
t.save_as("image.svg")
```
png:
![image](https://user-images.githubusercontent.com/42113979/153001103-19712964-94e7-491c-bba4-3bcfd4d06dcf.png)
svg:
![image](https://user-images.githubusercontent.com/42113979/153001141-ea5d5dae-1576-4481-9a8c-af5ce8969c54.svg)

**Comment by donkirkby** [comment]
Possible workaround in `SvgTurtle.dot()`: switch from a line of length 0 with rounded ends to a line of length .0001. That looks identical, but doesn't get filtered out by svglib.

**Comment by inteon** [comment]
I'm working together with @BTWS2 on a Dodona judge (https://dodona.ugent.be/en/) with support for turtle.

**Comment by donkirkby** [comment]
I created issue deeplook/svglib#319. Are you happy to use cairo, or would you like me to add a workaround until svglib fixes their issue?

**Comment by inteon** [comment]
Thanks for the effort. Cairo works fine for me at the moment.

**Comment by donkirkby** [comment]
The svglib project accepted my merge request, so you should be able to switch back to it when the next release after v1.2.1 comes out (if you want to).
